version: '3.8'
services:
  sdrplusplus:
    build:
      context: .
    image: sdrplusplus:latest
    init: true
    network_mode: host

    device_cgroup_rules:
      - 'c 189:* rwm'
    devices:
      - '/dev/bus/usb'
    volumes:
      - type: 'volume'
        source: 'sdrplusplus'
        target: '/opt/sdrpp'
    restart: 'unless-stopped'
    stop_grace_period: 1s

volumes:
  sdrplusplus:
